import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NextIntlClientProvider} from 'next-intl';

const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'id'}];
}

export const metadata: Metadata = {
  title: 'Gyloop | Make Business Connected',
  description: 'Generated by create next app',
}



export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string },
}) {

  let messages;
 async function loadMessageTranslate() {
    switch (locale) {
      case 'en':
        return import(`@/translate/en.json`);
      case 'id':
        return import(`@/translate/id.json`);
      default:
        return import(`@/translate/en.json`);
    }
  }

  messages = (await loadMessageTranslate()).default;

  
  return (
    <html lang={locale}>
      <body className={inter.className} suppressContentEditableWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
